# image will be published to ghcr.io/<user>/<name>
name: os-thingy
# description will be included in the image's metadata
description: An attempt to make a (somewhat) usable fedora image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: configs/ostree.yml
  - from-file: configs/flatpaks.yml
  - from-file: configs/extensions.yml
  - from-file: configs/system_things.yml
  - from-file: configs/akmods.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

