modules:
  - type: rpm-ostree
    repos:
      - xanmod.repo
    install:
      - kernel-xanmod-edge
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-extra
